services:
  ai-customer-api:
    build:
      context: ./backend
    container_name: ai-customer-api
    env_file:
      - ./backend/.env
    ports:
      - "8010:8000"
    restart: always
    networks:
      - docker-net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.customer-api.rule=Host(`intership-api.hqsolutions.vn`)"
      - "traefik.http.routers.customer-api.entrypoints=websecure"
      - "traefik.http.routers.customer-api.tls.certresolver=myresolver"
      - "traefik.http.services.customer-api.loadbalancer.server.port=8000"

  ai-customer-web:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: ai-customer-web
    env_file:
      - ./frontend/.env
    ports:
      - "3010:3000"
    depends_on:
      - ai-customer-api
    restart: always
    networks:
      - docker-net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.customer-web.rule=Host(`intership.hqsolutions.vn`)"
      - "traefik.http.routers.customer-web.entrypoints=websecure"
      - "traefik.http.routers.customer-web.tls.certresolver=myresolver"
      - "traefik.http.services.customer-web.loadbalancer.server.port=3000"

networks:
  docker-net:
    external: true
