services:
  ai-customer-api:
    build:
      context: ./backend
    container_name: ai-customer-api
    env_file:
      - ./backend/.env
    ports:
      - "8010:8000"
    restart: always
    networks:
      - default
      - docker-net

  ai-customer-web:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: ai-customer-web
    env_file:
      - ./frontend/.env
    ports:
      - "3010:3000"
    depends_on:
      - ai-customer-api
    restart: always

networks:
  docker-net:
    external: true
